version: "3.8"
services:
  redis-server:
    image: "redis/redis-stack-server:latest"
    volumes:
      - ./configurations/redis/data:/data
      - ./configurations/redis/conf:/conf
    ports:
      - "127.0.0.1:6379:6379"
    entrypoint: redis-server
    command: /conf/redis.conf
    deploy:
      restart_policy:
        condition: on-failure
  node-server:
    image: "sage3/next:amd64"
    ports:
      - "443:443"
    depends_on:
      - "redis-server"
    volumes:
      - ./configurations/node/keys:/app/keys
      - ./configurations/node/assets:/app/dist/apps/homebase/assets
      - ./configurations/node/sage3-prod.hjson:/app/sage3-prod.hjson
    restart: always
  python:
    image: "sage3/foresight:latest"
    environment:
      - ENVIRONMENT=production
      - SAGE3_SERVER=${HOST}
      - ROOM_ID=a50f5a4d-59ed-4026-8d3c-786a9b7b61e7
    restart: always
    working_dir: /app
    command: python proxy.py
    depends_on:
      - "redis-server"
      - "jupyter"
      - "node-server"
  jupyter:
    image: "jupyter/datascience-notebook"
    volumes:
      - ./configurations/jupyter/conf:/conf
      - ./configurations/jupyter/notebooks:/home/jovyan/notebooks
      - ./redis-client:/home/jovyan/work
    ports:
      - "4443:8888"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - "redis-server"
    command: /conf/start.sh
    restart: always
